source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'PKCustomAlertView_Example', :exclusive => true do
  pod "PKCustomAlertView", :path => "../"
end

target 'PKCustomAlertView_Tests', :exclusive => true do
  pod "PKCustomAlertView", :path => "../"

  
end
